# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
keywords: závěť, poslední vůle, sepsání závěti, vydědění, Moje Závěť, mojezavet.cz, poslední slova, MojeZávěť, jak napsat závěť
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mojezavet.cz/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
